version: "3.6"
services:

  moo:
    container_name: moo
    image: lambdamoo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
    hostname: moo
    networks:
      - moo-backend
    extra_hosts:
      - host.docker.internal:host-gateway
    stop_signal: SIGKILL
    restart: always
    healthcheck:
      # test: curl -f http://localhost:7777 || exit 1
      test: netstat -ltn | grep -c 7777 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"  
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - ./data/moo/moo.db:/home/moo/lambdamoo/moo.db

  moo-proxy:
    container_name: moo-proxy
    image: haproxytech/haproxy-alpine:2.4
    hostname: moo-proxy
    ports:
      # - "80:80"
      # - "443:443"
      - 17777:17777
      - 17778:17778
    depends_on:
      - "moo"
    networks:
      - moo-frontend
      - moo-backend
    extra_hosts:
      - host.docker.internal:host-gateway
    stop_signal: SIGKILL
    restart: always
    healthcheck:
      test: curl -f http://localhost:17777 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./data/proxy:/usr/local/etc/haproxy
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot

  moo-certs:
    container_name: moo-certs
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    hostname: moo-certs
    depends_on:
      - "moo"
      - "moo-proxy"
    networks:
      - moo-frontend
    extra_hosts:
      - host.docker.internal:host-gateway
    stop_signal: SIGKILL
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot    

networks:
  moo-frontend:
    name: moo-frontend
    driver: bridge
  moo-backend:
    name: moo-backend
    driver: bridge