version: "3.9"
services:

  lambdamoo:
    container_name: lambdamoo
    image: lambdamoo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
    ports:
      - "7777:7777"
    networks:
      - backend
    healthcheck:
      # test: curl -f http://localhost:7777 || exit 1
      test: netstat -ltn | grep -c 7777 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "lambdamoo"
    networks:
      - frontend
      - backend
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    container_name: certbot
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - "lambdamoo"
      - "nginx"
    networks:
      - backend
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot    

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge
